# Generated by Django 4.0.5 on 2022-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_price_id',
            field=models.CharField(default='price_1LCfzGHbrOhTO2jzGrkrAkqm', max_length=200),
        ),
    ]
