# Generated by Django 4.0.5 on 2022-06-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Professional', 'pro'), ('Professional+', 'pro+'), ('Free', 'free')], default='Free', max_length=30),
        ),
        migrations.AlterField(
            model_name='usersubsription',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
